// source: movie.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.moviePackage.AllMovieResponse', null, global);
goog.exportSymbol('proto.moviePackage.B64Image', null, global);
goog.exportSymbol('proto.moviePackage.Empty', null, global);
goog.exportSymbol('proto.moviePackage.Movie', null, global);
goog.exportSymbol('proto.moviePackage.SearchMovieRequest', null, global);
goog.exportSymbol('proto.moviePackage.SearchMovieResponse', null, global);
goog.exportSymbol('proto.moviePackage.UpdateMovieInfoRequest', null, global);
goog.exportSymbol('proto.moviePackage.UpdateMovieInfoResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.UpdateMovieInfoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.moviePackage.UpdateMovieInfoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.UpdateMovieInfoRequest.displayName = 'proto.moviePackage.UpdateMovieInfoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.UpdateMovieInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.moviePackage.UpdateMovieInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.UpdateMovieInfoResponse.displayName = 'proto.moviePackage.UpdateMovieInfoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.moviePackage.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.Empty.displayName = 'proto.moviePackage.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.AllMovieResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.moviePackage.AllMovieResponse.repeatedFields_, null);
};
goog.inherits(proto.moviePackage.AllMovieResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.AllMovieResponse.displayName = 'proto.moviePackage.AllMovieResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.SearchMovieRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.moviePackage.SearchMovieRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.SearchMovieRequest.displayName = 'proto.moviePackage.SearchMovieRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.B64Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.moviePackage.B64Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.B64Image.displayName = 'proto.moviePackage.B64Image';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.Movie = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.moviePackage.Movie, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.Movie.displayName = 'proto.moviePackage.Movie';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.moviePackage.SearchMovieResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.moviePackage.SearchMovieResponse.repeatedFields_, null);
};
goog.inherits(proto.moviePackage.SearchMovieResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.moviePackage.SearchMovieResponse.displayName = 'proto.moviePackage.SearchMovieResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.UpdateMovieInfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.UpdateMovieInfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.UpdateMovieInfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.UpdateMovieInfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    moviename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    newscreeninginfo: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.UpdateMovieInfoRequest}
 */
proto.moviePackage.UpdateMovieInfoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.UpdateMovieInfoRequest;
  return proto.moviePackage.UpdateMovieInfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.UpdateMovieInfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.UpdateMovieInfoRequest}
 */
proto.moviePackage.UpdateMovieInfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoviename(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewscreeninginfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.UpdateMovieInfoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.UpdateMovieInfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.UpdateMovieInfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.UpdateMovieInfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMoviename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNewscreeninginfo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string movieName = 1;
 * @return {string}
 */
proto.moviePackage.UpdateMovieInfoRequest.prototype.getMoviename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.UpdateMovieInfoRequest} returns this
 */
proto.moviePackage.UpdateMovieInfoRequest.prototype.setMoviename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string newScreeningInfo = 2;
 * @return {string}
 */
proto.moviePackage.UpdateMovieInfoRequest.prototype.getNewscreeninginfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.UpdateMovieInfoRequest} returns this
 */
proto.moviePackage.UpdateMovieInfoRequest.prototype.setNewscreeninginfo = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.UpdateMovieInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.UpdateMovieInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.UpdateMovieInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.UpdateMovieInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.UpdateMovieInfoResponse}
 */
proto.moviePackage.UpdateMovieInfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.UpdateMovieInfoResponse;
  return proto.moviePackage.UpdateMovieInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.UpdateMovieInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.UpdateMovieInfoResponse}
 */
proto.moviePackage.UpdateMovieInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.UpdateMovieInfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.UpdateMovieInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.UpdateMovieInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.UpdateMovieInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool status = 1;
 * @return {boolean}
 */
proto.moviePackage.UpdateMovieInfoResponse.prototype.getStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.moviePackage.UpdateMovieInfoResponse} returns this
 */
proto.moviePackage.UpdateMovieInfoResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.Empty}
 */
proto.moviePackage.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.Empty;
  return proto.moviePackage.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.Empty}
 */
proto.moviePackage.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.moviePackage.AllMovieResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.AllMovieResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.AllMovieResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.AllMovieResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.AllMovieResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    moviesList: jspb.Message.toObjectList(msg.getMoviesList(),
    proto.moviePackage.Movie.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.AllMovieResponse}
 */
proto.moviePackage.AllMovieResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.AllMovieResponse;
  return proto.moviePackage.AllMovieResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.AllMovieResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.AllMovieResponse}
 */
proto.moviePackage.AllMovieResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.moviePackage.Movie;
      reader.readMessage(value,proto.moviePackage.Movie.deserializeBinaryFromReader);
      msg.addMovies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.AllMovieResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.AllMovieResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.AllMovieResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.AllMovieResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMoviesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.moviePackage.Movie.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Movie movies = 1;
 * @return {!Array<!proto.moviePackage.Movie>}
 */
proto.moviePackage.AllMovieResponse.prototype.getMoviesList = function() {
  return /** @type{!Array<!proto.moviePackage.Movie>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.moviePackage.Movie, 1));
};


/**
 * @param {!Array<!proto.moviePackage.Movie>} value
 * @return {!proto.moviePackage.AllMovieResponse} returns this
*/
proto.moviePackage.AllMovieResponse.prototype.setMoviesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.moviePackage.Movie=} opt_value
 * @param {number=} opt_index
 * @return {!proto.moviePackage.Movie}
 */
proto.moviePackage.AllMovieResponse.prototype.addMovies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.moviePackage.Movie, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.moviePackage.AllMovieResponse} returns this
 */
proto.moviePackage.AllMovieResponse.prototype.clearMoviesList = function() {
  return this.setMoviesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.SearchMovieRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.SearchMovieRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.SearchMovieRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.SearchMovieRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    moviename: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.SearchMovieRequest}
 */
proto.moviePackage.SearchMovieRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.SearchMovieRequest;
  return proto.moviePackage.SearchMovieRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.SearchMovieRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.SearchMovieRequest}
 */
proto.moviePackage.SearchMovieRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoviename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.SearchMovieRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.SearchMovieRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.SearchMovieRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.SearchMovieRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMoviename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string movieName = 1;
 * @return {string}
 */
proto.moviePackage.SearchMovieRequest.prototype.getMoviename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.SearchMovieRequest} returns this
 */
proto.moviePackage.SearchMovieRequest.prototype.setMoviename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.B64Image.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.B64Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.B64Image} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.B64Image.toObject = function(includeInstance, msg) {
  var f, obj = {
    b64image: msg.getB64image_asB64(),
    width: jspb.Message.getFieldWithDefault(msg, 2, 0),
    height: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.B64Image}
 */
proto.moviePackage.B64Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.B64Image;
  return proto.moviePackage.B64Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.B64Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.B64Image}
 */
proto.moviePackage.B64Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setB64image(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.B64Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.B64Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.B64Image} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.B64Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getB64image_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional bytes b64image = 1;
 * @return {string}
 */
proto.moviePackage.B64Image.prototype.getB64image = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes b64image = 1;
 * This is a type-conversion wrapper around `getB64image()`
 * @return {string}
 */
proto.moviePackage.B64Image.prototype.getB64image_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getB64image()));
};


/**
 * optional bytes b64image = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getB64image()`
 * @return {!Uint8Array}
 */
proto.moviePackage.B64Image.prototype.getB64image_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getB64image()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.moviePackage.B64Image} returns this
 */
proto.moviePackage.B64Image.prototype.setB64image = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional int32 width = 2;
 * @return {number}
 */
proto.moviePackage.B64Image.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.moviePackage.B64Image} returns this
 */
proto.moviePackage.B64Image.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 height = 3;
 * @return {number}
 */
proto.moviePackage.B64Image.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.moviePackage.B64Image} returns this
 */
proto.moviePackage.B64Image.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.Movie.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.Movie.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.Movie} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.Movie.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subtitle: jspb.Message.getFieldWithDefault(msg, 3, ""),
    titleimg: (f = msg.getTitleimg()) && proto.moviePackage.B64Image.toObject(includeInstance, f),
    backgroundimg: (f = msg.getBackgroundimg()) && proto.moviePackage.B64Image.toObject(includeInstance, f),
    cardimg: (f = msg.getCardimg()) && proto.moviePackage.B64Image.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 7, ""),
    theatre: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.Movie}
 */
proto.moviePackage.Movie.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.Movie;
  return proto.moviePackage.Movie.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.Movie} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.Movie}
 */
proto.moviePackage.Movie.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubtitle(value);
      break;
    case 4:
      var value = new proto.moviePackage.B64Image;
      reader.readMessage(value,proto.moviePackage.B64Image.deserializeBinaryFromReader);
      msg.setTitleimg(value);
      break;
    case 5:
      var value = new proto.moviePackage.B64Image;
      reader.readMessage(value,proto.moviePackage.B64Image.deserializeBinaryFromReader);
      msg.setBackgroundimg(value);
      break;
    case 6:
      var value = new proto.moviePackage.B64Image;
      reader.readMessage(value,proto.moviePackage.B64Image.deserializeBinaryFromReader);
      msg.setCardimg(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTheatre(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.Movie.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.Movie.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.Movie} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.Movie.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubtitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitleimg();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.moviePackage.B64Image.serializeBinaryToWriter
    );
  }
  f = message.getBackgroundimg();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.moviePackage.B64Image.serializeBinaryToWriter
    );
  }
  f = message.getCardimg();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.moviePackage.B64Image.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTheatre();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.moviePackage.Movie.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.moviePackage.Movie.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string subTitle = 3;
 * @return {string}
 */
proto.moviePackage.Movie.prototype.getSubtitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.setSubtitle = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional B64Image titleImg = 4;
 * @return {?proto.moviePackage.B64Image}
 */
proto.moviePackage.Movie.prototype.getTitleimg = function() {
  return /** @type{?proto.moviePackage.B64Image} */ (
    jspb.Message.getWrapperField(this, proto.moviePackage.B64Image, 4));
};


/**
 * @param {?proto.moviePackage.B64Image|undefined} value
 * @return {!proto.moviePackage.Movie} returns this
*/
proto.moviePackage.Movie.prototype.setTitleimg = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.clearTitleimg = function() {
  return this.setTitleimg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.moviePackage.Movie.prototype.hasTitleimg = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional B64Image backgroundImg = 5;
 * @return {?proto.moviePackage.B64Image}
 */
proto.moviePackage.Movie.prototype.getBackgroundimg = function() {
  return /** @type{?proto.moviePackage.B64Image} */ (
    jspb.Message.getWrapperField(this, proto.moviePackage.B64Image, 5));
};


/**
 * @param {?proto.moviePackage.B64Image|undefined} value
 * @return {!proto.moviePackage.Movie} returns this
*/
proto.moviePackage.Movie.prototype.setBackgroundimg = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.clearBackgroundimg = function() {
  return this.setBackgroundimg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.moviePackage.Movie.prototype.hasBackgroundimg = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional B64Image cardImg = 6;
 * @return {?proto.moviePackage.B64Image}
 */
proto.moviePackage.Movie.prototype.getCardimg = function() {
  return /** @type{?proto.moviePackage.B64Image} */ (
    jspb.Message.getWrapperField(this, proto.moviePackage.B64Image, 6));
};


/**
 * @param {?proto.moviePackage.B64Image|undefined} value
 * @return {!proto.moviePackage.Movie} returns this
*/
proto.moviePackage.Movie.prototype.setCardimg = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.clearCardimg = function() {
  return this.setCardimg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.moviePackage.Movie.prototype.hasCardimg = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string type = 7;
 * @return {string}
 */
proto.moviePackage.Movie.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string theatre = 8;
 * @return {string}
 */
proto.moviePackage.Movie.prototype.getTheatre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.moviePackage.Movie} returns this
 */
proto.moviePackage.Movie.prototype.setTheatre = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.moviePackage.SearchMovieResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.moviePackage.SearchMovieResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.moviePackage.SearchMovieResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.moviePackage.SearchMovieResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.SearchMovieResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    exist: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    movieList: jspb.Message.toObjectList(msg.getMovieList(),
    proto.moviePackage.Movie.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.moviePackage.SearchMovieResponse}
 */
proto.moviePackage.SearchMovieResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.moviePackage.SearchMovieResponse;
  return proto.moviePackage.SearchMovieResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.moviePackage.SearchMovieResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.moviePackage.SearchMovieResponse}
 */
proto.moviePackage.SearchMovieResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExist(value);
      break;
    case 2:
      var value = new proto.moviePackage.Movie;
      reader.readMessage(value,proto.moviePackage.Movie.deserializeBinaryFromReader);
      msg.addMovie(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.moviePackage.SearchMovieResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.moviePackage.SearchMovieResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.moviePackage.SearchMovieResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.moviePackage.SearchMovieResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExist();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMovieList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.moviePackage.Movie.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool exist = 1;
 * @return {boolean}
 */
proto.moviePackage.SearchMovieResponse.prototype.getExist = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.moviePackage.SearchMovieResponse} returns this
 */
proto.moviePackage.SearchMovieResponse.prototype.setExist = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated Movie movie = 2;
 * @return {!Array<!proto.moviePackage.Movie>}
 */
proto.moviePackage.SearchMovieResponse.prototype.getMovieList = function() {
  return /** @type{!Array<!proto.moviePackage.Movie>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.moviePackage.Movie, 2));
};


/**
 * @param {!Array<!proto.moviePackage.Movie>} value
 * @return {!proto.moviePackage.SearchMovieResponse} returns this
*/
proto.moviePackage.SearchMovieResponse.prototype.setMovieList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.moviePackage.Movie=} opt_value
 * @param {number=} opt_index
 * @return {!proto.moviePackage.Movie}
 */
proto.moviePackage.SearchMovieResponse.prototype.addMovie = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.moviePackage.Movie, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.moviePackage.SearchMovieResponse} returns this
 */
proto.moviePackage.SearchMovieResponse.prototype.clearMovieList = function() {
  return this.setMovieList([]);
};


goog.object.extend(exports, proto.moviePackage);
